[prepare_manpage] Write to files directly instead of redirection
On Linux, LC_ALL=any locale with charset other than UTF-8 makes print()
try to encode the string with a different encoding.

$ LC_ALL=C PYTHON=python3 make youtube-dl.1
python3 devscripts/prepare_manpage.py >youtube-dl.1.temp.md
Traceback (most recent call last):
  File "devscripts/prepare_manpage.py", line 63, in <module>
    print(readme)
UnicodeEncodeError: 'ascii' codec can't encode character '\u4e2d' in position 19370: ordinal not in range(128)
Makefile:76: recipe for target 'youtube-dl.1' failed
make: *** [youtube-dl.1] Error 1